const mongoose=require("mongoose");
const BillSchema=new mongoose.Schema({
    c_address:{
        type:String,
        require:true
    },
    c_district:{
        type:String,
        require:true
    },
    c_email:{
        type:String,
        require:true
    },
    c_id:{
        type:String,
        require:true
    },
    c_landmark:{
        type:String,
        require:true
    },
    c_msg:{
        type:String,
        require:true
    },
    c_name:{
        type:String,
        require:true
    },
    c_phn:{
        type:String,
        require:true
    },
    paymentmethod:{
        type:String,
        require:true
    },
    products:{
        type:Array,
        require:true
    },
    subtotal:{
        type:Number,
        require:true
    },
},{timestamps:true});
module.exports=mongoose.model("Bill",BillSchema);